#!/bin/bash
set -e

echo "🔍 Checking prerequisites..."

if [ ! -f "package.json" ]; then
    echo "❌ 'package.json' not found. Run from frontend directory."
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo "❌ 'npm' is not installed."
    exit 1
fi

echo "✅ Prerequisites fulfilled."
echo ""

echo "📦 Collecting license information..."

PROJECT_NAME=$(jq -r '.name' package.json)
PROJECT_VERSION=$(jq -r '.version' package.json)

{
    echo "# THIRD-PARTY NOTICES"
    echo ""
    echo "This project ($PROJECT_NAME v$PROJECT_VERSION) uses the following open-source packages."
    echo "Generated on: $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""
    echo "## Dependencies"
    echo ""
} > THIRD-PARTY-NOTICES.txt

npm ls --depth=0 --production 2>/dev/null | sed '1d' >> THIRD-PARTY-NOTICES.md || true

{
    echo ""
    echo "---"
    echo "Generated by: generate-third-party-notices.sh"
} >> THIRD-PARTY-NOTICES.txt

echo "✅ THIRD-PARTY-NOTICES.txt successfully generated!"
echo ""
echo "📄 Preview (first 50 lines):"
head -50 THIRD-PARTY-NOTICES.txt
echo ""
echo "📁 File location: $(pwd)/THIRD-PARTY-NOTICES.txt"
