events {}

http {
    log_format no_query_string '$remote_addr - $remote_user [$time_local] '
                                '"$request_method $uri $server_protocol" $status $body_bytes_sent '
                                '"$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log no_query_string;

    server {
        listen 80;
		client_max_body_size 10G;

        # Backend
        location /api/ {
            proxy_pass http://backend:8095/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_buffering off;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
        
        # SignalR-Hub (WebSocket)
       location /emailProgress {
                   proxy_pass http://backend:8095/emailProgress;
                   proxy_set_header Host $host;
                   proxy_set_header X-Real-IP $remote_addr;
       
                   proxy_http_version 1.1;
                   proxy_set_header Upgrade $http_upgrade;
                   proxy_set_header Connection "upgrade";
       
                   proxy_read_timeout 86400s;
                   proxy_send_timeout 86400s;
               }

        # Frontend
        location / {
            proxy_pass http://frontend:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}