events {}

http {
    server {
        listen 80;
		
		client_max_body_size 50M;

        # Backend
        location /api/ {
            proxy_pass http://backend:8095/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        
        # SignalR-Hub (WebSocket)
       location /emailProgress {
                   proxy_pass http://backend:8095/emailProgress;
                   proxy_set_header Host $host;
                   proxy_set_header X-Real-IP $remote_addr;
       
                   proxy_http_version 1.1;
                   proxy_set_header Upgrade $http_upgrade;
                   proxy_set_header Connection "upgrade";
       
                   proxy_read_timeout 86400s;
                   proxy_send_timeout 86400s;
               }

        # Frontend
        location / {
            proxy_pass http://frontend:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}