// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniVerein.DAL.Data;

#nullable disable

namespace UniVerein.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603175537_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UniVerein.DAL.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Entity")
                        .HasColumnType("longtext")
                        .HasColumnName("entity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.ContributionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<Guid>("ExportId")
                        .HasColumnType("char(36)")
                        .HasColumnName("exportId");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset?>("Paid")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("paid");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Contributions");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.ContributionPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("interval");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ContributionPlans");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.CreditorConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Bic_Encrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("bic_encrypted");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext")
                        .HasColumnName("city_name");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreditorId")
                        .HasColumnType("longtext")
                        .HasColumnName("creditor_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Iban_Encrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("iban_encrypted");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PostCode")
                        .HasColumnType("longtext")
                        .HasColumnName("post_code");

                    b.Property<string>("StreetNameAndNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("street_name_and_number");

                    b.HasKey("Id");

                    b.ToTable("CreditorConfigs");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.LinkSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext")
                        .HasColumnName("icon");

                    b.Property<string>("Link")
                        .HasColumnType("longtext")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("LinkSettings");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.MailSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable_ssl");

                    b.Property<string>("FromMail")
                        .HasColumnType("longtext")
                        .HasColumnName("from_mail");

                    b.Property<int>("ImapPort")
                        .HasColumnType("int")
                        .HasColumnName("imap_port");

                    b.Property<string>("ImapServer")
                        .HasColumnType("longtext")
                        .HasColumnName("imap_server");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("longtext")
                        .HasColumnName("smtp_server");

                    b.Property<string>("Username")
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("MailSettings");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.MemberCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("MemberCategories");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.MemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AcademicDegree")
                        .HasColumnType("longtext")
                        .HasColumnName("academic_degree");

                    b.Property<string>("Bic_Encrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("bic_encrypted");

                    b.Property<string>("BirthdayEncrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("birthday");

                    b.Property<string>("BulkMail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bulk_mail");

                    b.Property<string>("City")
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<Guid?>("ContributionPlanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("contribution_plan_id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<string>("CourseOfStudy")
                        .HasColumnType("longtext")
                        .HasColumnName("course_of_study");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmailEncrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("emailEncrypted");

                    b.Property<string>("EmailHash")
                        .HasColumnType("longtext")
                        .HasColumnName("emailHash");

                    b.Property<DateTimeOffset?>("EndOfStudies")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_of_studies");

                    b.Property<DateTimeOffset>("EntryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("entry_date");

                    b.Property<DateTimeOffset?>("ExitDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("exit_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<string>("IBAN_Encrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("iban_encrypted");

                    b.Property<string>("IBAN_Hash")
                        .HasColumnType("longtext")
                        .HasColumnName("iban_hash");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("MandateId")
                        .HasColumnType("longtext")
                        .HasColumnName("mandate_id");

                    b.Property<Guid?>("MemberCategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_category_id");

                    b.Property<int>("MemberNumber")
                        .HasColumnType("int")
                        .HasColumnName("member_number");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext")
                        .HasColumnName("middle_name");

                    b.Property<string>("PhoneEncrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext")
                        .HasColumnName("postal_code");

                    b.Property<DateTimeOffset?>("SepaConsent")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sepa_consent");

                    b.Property<DateTimeOffset>("StartOfStudies")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_of_studies");

                    b.Property<string>("StreetEncrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("street");

                    b.Property<string>("TaskWithinTheClub")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("task_within_the_club");

                    b.HasKey("Id");

                    b.HasIndex("ContributionPlanId");

                    b.HasIndex("MemberCategoryId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.SepaExportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("exportedCases");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("SepaExport");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BlockingLoginTimeout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("blocking_login_timeout");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.WebPageConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext")
                        .HasColumnName("logo");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext")
                        .HasColumnName("page_name");

                    b.HasKey("Id");

                    b.ToTable("web_page_config");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("UniVerein.DAL.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.ContributionEntity", b =>
                {
                    b.HasOne("UniVerein.DAL.Entities.MemberEntity", "MemberEntity")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberEntity");
                });

            modelBuilder.Entity("UniVerein.DAL.Entities.MemberEntity", b =>
                {
                    b.HasOne("UniVerein.DAL.Entities.ContributionPlanEntity", "ContributionPlan")
                        .WithMany()
                        .HasForeignKey("ContributionPlanId");

                    b.HasOne("UniVerein.DAL.Entities.MemberCategoryEntity", "MemberCategory")
                        .WithMany()
                        .HasForeignKey("MemberCategoryId");

                    b.Navigation("ContributionPlan");

                    b.Navigation("MemberCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
