name: Cleanup old branch images

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  cleanup-branch-images:
    name: Cleanup Branch Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete stale/orphaned images older than 2 days
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.PAT_PACKAGES }}
          owner: uni-verein
          packages: univerein-backend,univerein-frontend,univerein-db-migrator
          exclude-tags: 'keep-*,*.*.*'
          delete-tags: '???????'
          delete-untagged: true
          older-than: '2 days'
          dry-run: false
          validate: true
